# Generated by Django 4.2.7 on 2026-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_orderedslip_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_location',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('SHOP', 'Shop')], default='WAREHOUSE', max_length=50),
        ),
    ]
