# Generated by Django 4.2.7 on 2026-07-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_shop_stock_product_warehouse_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_from_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
