# Generated by Django 4.2.7 on 2026-07-17 21:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_barcode_product_pack_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
